# Generated by Django 5.2.3 on 2025-08-18 21:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(choices=[('breakfast', 'Café da manhã'), ('lunch', 'Almoço'), ('afternoon_snack', 'Lanche da tarde'), ('dinner', 'Jantar'), ('snack', 'Lanche')], max_length=20, unique=True)),
                ('interval_start', models.TimeField()),
                ('interval_end', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('pdf_file', models.FileField(upload_to='nutrition_plans/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('start_plan', models.DateField()),
                ('end_plan', models.DateField()),
                ('lifetime', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.DateTimeField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('base_points', models.FloatField(blank=True, editable=False, null=True)),
                ('multiplier', models.FloatField(default=1.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('validation_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.mealconfig')),
            ],
        ),
        migrations.CreateModel(
            name='MealProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='meal/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4'])])),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='nutrition.meal')),
            ],
        ),
        migrations.CreateModel(
            name='MealStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_meal_datetime', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
