# Generated by Django 5.2.3 on 2025-11-19 22:59

import django.db.models.deletion
import nutrition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_meal_user'),
        ('status', '0005_alter_status_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='validation_status',
            field=models.ForeignKey(default=nutrition.models.get_published_status_id, on_delete=django.db.models.deletion.PROTECT, to='status.status'),
        ),
    ]
