# Generated by Django 5.2.3 on 2026-01-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_alter_meal_validation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealconfig',
            options={'ordering': ['interval_start']},
        ),
        migrations.AddField(
            model_name='meal',
            name='fasting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mealconfig',
            name='meal_name',
            field=models.CharField(choices=[('breakfast', 'Café da manhã'), ('lunch', 'Almoço'), ('afternoon_snack', 'Lanche da tarde'), ('dinner', 'Jantar'), ('snack', 'Lanche da manhã')], max_length=20, unique=True),
        ),
    ]
