# Generated by Django 5.2.3 on 2026-03-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_group_photo'),
        ('nutrition', '0004_alter_mealconfig_options_meal_fasting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='groups',
            field=models.ManyToManyField(blank=True, to='groups.group'),
        ),
    ]
