"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
import os
from pathlib import Path

try:
    from .local_settings import *
except ImportError:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
        }
    }

    # Cloudflare R2 configuration for production
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL')
    AWS_S3_REGION_NAME = 'auto'
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 3600
    AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN', None)
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_S3_URL_PROTOCOL = 'https:'
    AWS_S3_ADDRESSING_STYLE = 'path'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'val-temp' if not os.getenv('SECRET_KEY') else os.getenv('SECRET_KEY')
if 'SECRET_KEY' in os.environ:
    SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver', 'api.startbeneficios.com.br']
CORS_ORIGIN_ALLOW_ALL = True  # TODO: Change to False in production

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'drf_spectacular',
    'corsheaders',
    'storages',
    'django_extensions',
    'gamification.apps.GamificationConfig',
    'clients.apps.ClientsConfig',
    'authentication.apps.AuthenticationConfig',
    'profiles.apps.ProfilesConfig',
    'groups.apps.GroupsConfig',
    'workouts.apps.WorkoutsConfig',
    'status.apps.StatusConfig',
    'nutrition.apps.NutritionConfig',
    'social_feed.apps.SocialFeedConfig',
    'analytics.apps.AnalyticsConfig',
    'notifications.apps.NotificationsConfig',
    'django_apscheduler',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Xpump API',
    'DESCRIPTION': 'Documentation from endpoints of Xpump API',
    'VERSION': '0.0.1',
    'SERVE_INCLUDE_SCHEMA': False,  # se não quiser incluir o JSON do schema no Swagger UI
    # qualquer outra opção da doc: https://drf-spectacular.readthedocs.io/
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Cloudflare R2 Storage Configuration (Django 4.2+)
STORAGES = {
    "default": {
        "BACKEND": "core.storage_backends.CloudflareR2Storage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Compatibilidade com Django antigo
DEFAULT_FILE_STORAGE = 'core.storage_backends.CloudflareR2Storage'

# Media URL - use custom domain if available, otherwise use R2 endpoint
try:
    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
    else:
        MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/"
except (NameError, AttributeError):
    MEDIA_URL = 'media/'

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build')

SIMPLE_JWT = {
    # Tempo de vida do token de refresh (padrão: 1 dia)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------- #
# Web Push (VAPID) - chaves definidas em local_settings.py ou env vars          #
# ---------------------------------------------------------------------------- #
VAPID_PRIVATE_KEY = os.getenv('VAPID_PRIVATE_KEY', globals().get('VAPID_PRIVATE_KEY', ''))
VAPID_PUBLIC_KEY = os.getenv('VAPID_PUBLIC_KEY', globals().get('VAPID_PUBLIC_KEY', ''))
VAPID_ADMIN_EMAIL = os.getenv('VAPID_ADMIN_EMAIL', globals().get('VAPID_ADMIN_EMAIL', 'admin@xpump.com'))

# ---------------------------------------------------------------------------- #
# APScheduler                                                                    #
# ---------------------------------------------------------------------------- #
APSCHEDULER_DATETIME_FORMAT = 'N j, Y, f:s a'
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # segundos

# ---------------------------------------------------------------------------- #
# Logging                                                                        #
# ---------------------------------------------------------------------------- #
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {module}.{funcName}:{lineno} — {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{asctime}] {levelname} — {message}',
            'style': '{',
            'datefmt': '%H:%M:%S',
        },
    },

    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },

    'handlers': {
        # Console — tudo em dev, WARNING+ em prod
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },

        # Arquivo geral (rotação diária, mantém 30 dias)
        'file_general': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': str(LOG_DIR / 'general.log'),
            'when': 'midnight',
            'interval': 1,
            'backupCount': 30,
            'encoding': 'utf-8',
            'formatter': 'verbose',
        },

        # Arquivo de erros (rotação diária, mantém 90 dias)
        'file_errors': {
            'level': 'ERROR',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': str(LOG_DIR / 'errors.log'),
            'when': 'midnight',
            'interval': 1,
            'backupCount': 90,
            'encoding': 'utf-8',
            'formatter': 'verbose',
        },

        # Arquivo de SQL queries (só em DEBUG)
        'file_sql': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': str(LOG_DIR / 'sql.log'),
            'when': 'midnight',
            'interval': 1,
            'backupCount': 7,
            'encoding': 'utf-8',
            'formatter': 'verbose',
        },

        # Arquivo de requests (rotação diária, mantém 30 dias)
        'file_requests': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': str(LOG_DIR / 'requests.log'),
            'when': 'midnight',
            'interval': 1,
            'backupCount': 30,
            'encoding': 'utf-8',
            'formatter': 'verbose',
        },
    },

    'loggers': {
        # Logger raiz do Django
        'django': {
            'handlers': ['console', 'file_general', 'file_errors'],
            'level': 'INFO',
            'propagate': False,
        },

        # Requests HTTP (4xx, 5xx)
        'django.request': {
            'handlers': ['file_requests', 'file_errors'],
            'level': 'INFO',
            'propagate': False,
        },

        # Server (runserver output)
        'django.server': {
            'handlers': ['console', 'file_requests'],
            'level': 'INFO',
            'propagate': False,
        },

        # SQL queries (só ativado em DEBUG)
        'django.db.backends': {
            'handlers': ['file_sql'],
            'level': 'DEBUG',
            'propagate': False,
        },

        # Security (CSRF, etc.)
        'django.security': {
            'handlers': ['file_errors', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },

        # ---- Loggers dos apps do projeto ---- #
        'authentication': {
            'handlers': ['console', 'file_general', 'file_errors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'profiles': {
            'handlers': ['console', 'file_general', 'file_errors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'groups': {
            'handlers': ['console', 'file_general', 'file_errors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'workouts': {
            'handlers': ['console', 'file_general', 'file_errors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'nutrition': {
            'handlers': ['console', 'file_general', 'file_errors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'gamification': {
            'handlers': ['console', 'file_general', 'file_errors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'clients': {
            'handlers': ['console', 'file_general', 'file_errors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'social_feed': {
            'handlers': ['console', 'file_general', 'file_errors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'analytics': {
            'handlers': ['console', 'file_general', 'file_errors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'notifications': {
            'handlers': ['console', 'file_general', 'file_errors'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
