# Generated by Django 5.2.3 on 2026-02-10 21:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_push', models.BooleanField(default=True, help_text='Enable push notifications')),
                ('enable_social', models.BooleanField(default=True, help_text='Enable social interaction notifications (likes, comments)')),
                ('enable_groups', models.BooleanField(default=True, help_text='Enable group notifications (invites, promotions)')),
                ('enable_achievements', models.BooleanField(default=True, help_text='Enable achievement notifications')),
                ('enable_reminders', models.BooleanField(default=True, help_text='Enable reminder notifications (workout, meal)')),
                ('enable_streaks', models.BooleanField(default=True, help_text='Enable streak milestone notifications')),
                ('enable_level_ups', models.BooleanField(default=True, help_text='Enable level up notifications')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (no push notifications)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours (no push notifications)', null=True)),
                ('user', models.OneToOneField(help_text='User these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('social', 'Social Interaction'), ('group', 'Group Activity'), ('achievement', 'Achievement'), ('streak', 'Streak Milestone'), ('reminder', 'Reminder'), ('level_up', 'Level Up'), ('rank_change', 'Rank Change')], help_text='Type of notification', max_length=20)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(help_text='Notification message content')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data specific to notification type (post_id, user_id, etc.)')),
                ('read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was marked as read', null=True)),
                ('sent_push', models.BooleanField(default=False, help_text='Whether a push notification was sent')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was created')),
                ('recipient', models.ForeignKey(help_text='User who will receive the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read', 'created_at'], name='notificatio_recipie_9c8dcc_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(help_text='Push service endpoint URL', max_length=500, validators=[django.core.validators.URLValidator()])),
                ('p256dh_key', models.CharField(help_text='P256DH key for encrypting push messages (base64 encoded)', max_length=255)),
                ('auth_key', models.CharField(help_text='Auth secret for encrypting push messages (base64 encoded)', max_length=255)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the browser')),
                ('active', models.BooleanField(default=True, help_text='Whether this subscription is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the subscription was created')),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time a push was sent to this subscription', null=True)),
                ('user', models.ForeignKey(help_text='User who owns this subscription', on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Subscription',
                'verbose_name_plural': 'Push Subscriptions',
                'indexes': [models.Index(fields=['user', 'active'], name='notificatio_user_id_e2798d_idx')],
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
