# Generated by Django 5.2.3 on 2025-09-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='app_name',
            field=models.CharField(choices=[('WORKOUT', 'Check-ins de treino'), ('NUTRITION', 'Posts de refeições'), ('COMMENT', 'Comentários')], max_length=120),
        ),
    ]
