# Generated by Django 5.2.3 on 2025-09-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_alter_status_app_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['app_name', 'action']},
        ),
        migrations.AlterField(
            model_name='status',
            name='app_name',
            field=models.CharField(choices=[('WORKOUT', 'Check-ins de treino'), ('NUTRITION', 'Posts de refeições')], max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('app_name', 'action', 'is_active')},
        ),
    ]
