# Generated by Django 5.2.3 on 2025-10-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_alter_status_options_alter_status_app_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='app_name',
            field=models.CharField(choices=[('WORKOUT', 'Check-ins de treino'), ('NUTRITION', 'Posts de refeições'), ('COMMENT', 'Comentários')], max_length=120),
        ),
    ]
