# Generated by Django 5.2.3 on 2025-11-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_alter_status_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='app_name',
            field=models.CharField(choices=[('WORKOUT', 'Check-ins de treino'), ('NUTRITION', 'Posts de refeições'), ('COMMENT', 'Comentários'), ('POST', 'Posts')], max_length=120),
        ),
    ]
