# Generated by Django 5.2.3 on 2025-07-04 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_members',
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
            preserve_default=False,
        ),
    ]
