# Generated by Django 5.2.3 on 2025-09-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_groupmembers_group_alter_groupmembers_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='invite_code',
        ),
        migrations.AddField(
            model_name='group',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
