# Generated by Django 5.2.3 on 2025-10-24 23:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Código do Cliente'),
        ),
    ]
