# Generated by Django 5.2.3 on 2025-11-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_client_groups_alter_client_owners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Telefone'),
        ),
    ]
