# Generated by Django 5.2.3 on 2025-12-17 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_client_phone'),
        ('groups', '0008_alter_group_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='groups',
            new_name='main_group',
        )
    ]
