# Generated by Django 5.2.3 on 2025-12-17 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_rename_client_groups_to_main_group'),
        ('groups', '0008_alter_group_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='clients', to='groups.group', verbose_name='Grupos'),
        ),
        migrations.AlterField(
            model_name='client',
            name='main_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='groups.group', verbose_name='Grupo principal'),
        ),
    ]
