# Generated by Django 5.2.3 on 2026-01-08 21:17

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_client_groups_alter_client_main_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_code',
            field=models.CharField(default=clients.models.clinet_code_generator, editable=False, max_length=8, verbose_name='Código do Cliente'),
        ),
    ]
