# Generated by Django 5.2.3 on 2025-07-09 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_type', models.CharField(choices=[('PHOTO', 'Foto'), ('VIDEO', 'Vídeo'), ('GEOLOCATION', 'Geolocalização')], max_length=100)),
                ('image_proof', models.ImageField(blank=True, null=True, upload_to='workout_checkins')),
                ('video_proof', models.FileField(blank=True, null=True, upload_to='workout_checkins')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True)),
                ('workout_date', models.DateTimeField()),
                ('base_points', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('validation_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
        ),
    ]
