# Generated by Django 5.2.3 on 2025-07-09 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutcheckin',
            name='video_proof',
            field=models.FileField(blank=True, help_text='Formatos suportados: MP4', null=True, upload_to='workout_checkins', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'], message='Apenas arquivos de vídeo MP4 são permitidos.')]),
        ),
    ]
