# Generated by Django 5.2.3 on 2025-07-12 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_workoutcheckin_multiplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutcheckin',
            name='image_proof',
        ),
        migrations.RemoveField(
            model_name='workoutcheckin',
            name='video_proof',
        ),
        migrations.AddField(
            model_name='workoutcheckin',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='workout_checkins/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4'])]),
        ),
    ]
