# Generated by Django 5.2.3 on 2025-07-12 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_remove_workoutcheckin_image_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutcheckin',
            name='proof_file',
            field=models.FileField(upload_to='workout_checkins/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4'])]),
        ),
    ]
