# Generated by Django 5.2.3 on 2025-07-12 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_alter_workoutcheckin_proof_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutcheckin',
            name='check_in_type',
        ),
    ]
