# Generated by Django 5.2.3 on 2025-07-12 19:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_remove_workoutcheckin_check_in_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutcheckin',
            name='proof_file',
        ),
        migrations.CreateModel(
            name='WorkoutCheckinProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='workout_checkins/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4'])])),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='workouts.workoutcheckin')),
            ],
        ),
    ]
