# Generated by Django 5.2.3 on 2025-07-18 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_remove_workoutcheckin_proof_file_workoutcheckinproof'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('pdf_file', models.FileField(upload_to='workout_plans/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('start_plan', models.DateField()),
                ('end_plan', models.DateField()),
                ('lifetime', models.BooleanField(default=False)),
            ],
        ),
    ]
