# Generated by Django 5.2.3 on 2025-08-13 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_workoutstreak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutstreak',
            name='last_workout_durations',
        ),
    ]
