# Generated by Django 5.2.3 on 2025-11-19 22:59

import django.db.models.deletion
import workouts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_alter_status_app_name'),
        ('workouts', '0012_alter_workoutcheckin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutcheckin',
            name='validation_status',
            field=models.ForeignKey(default=workouts.models.get_published_status_id, on_delete=django.db.models.deletion.PROTECT, to='status.status'),
        ),
    ]
