# Generated by Django 5.2.3 on 2026-01-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_alter_workoutcheckin_validation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutstreak',
            name='frequency',
            field=models.IntegerField(default=5),
        ),
    ]
