# Generated by Django 5.2.3 on 2026-03-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('workouts', '0014_alter_workoutstreak_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutcheckin',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
