# Generated by Django 5.2.3 on 2026-03-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_group_photo'),
        ('workouts', '0015_workoutcheckin_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutcheckin',
            name='groups',
            field=models.ManyToManyField(blank=True, to='groups.group'),
        ),
    ]
