# Generated by Django 5.2.3 on 2026-03-18 22:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0016_alter_workoutcheckin_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_duration', models.DurationField(default=datetime.timedelta(0))),
                ('workout_count', models.IntegerField(default=0)),
                ('awared_points', models.FloatField(default=0.0)),
                ('bonus_points', models.FloatField(default=0.0)),
                ('penalty_points', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
