# Generated by Django 5.2.3 on 2026-03-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0017_workoutdailysummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutDailySummary',
        ),
    ]
