# Generated by Django 5.2.3 on 2025-10-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_base', models.IntegerField(default=6, help_text='XP base para o nível 1')),
                ('exponential_factor', models.FloatField(default=1.5, help_text='Fator exponencial para cálculo de XP')),
                ('max_level', models.IntegerField(default=50, help_text='Nível máximo permitido')),
                ('workout_minutes', models.IntegerField(default=50, help_text='Minutos de treino para recompensar o XP estipulado')),
                ('workout_xp', models.IntegerField(default=2, help_text='XP concedido por completar os minutos de treino treino')),
                ('multiplier_workout_streak', models.JSONField(default={'first_streak_day': {'max_days': 4, 'min_days': 1, 'multiplier': 1.0}, 'fourth_streak_day': {'max_days': 39, 'min_days': 20, 'multiplier': 1.75}, 'last_streak_day': {'max_days': None, 'min_days': 40, 'multiplier': 2.0}, 'second_streak_day': {'max_days': 19, 'min_days': 5, 'multiplier': 1.25}, 'third_streak_day': {'max_days': 19, 'min_days': 10, 'multiplier': 1.5}}, help_text='Multiplicador de XP baseado na sequência de dias de atividade')),
                ('meal_xp', models.IntegerField(default=1, help_text='XP concedido por registrar uma refeição')),
                ('multiplier_meal_streak', models.JSONField(default={'first_streak_day': {'max_days': 1, 'min_days': 0, 'multiplier': 1.0}, 'fourth_streak_day': {'max_days': 31, 'min_days': 16, 'multiplier': 1.75}, 'last_streak_day': {'max_days': None, 'min_days': 32, 'multiplier': 2.0}, 'second_streak_day': {'max_days': 7, 'min_days': 2, 'multiplier': 1.25}, 'third_streak_day': {'max_days': 15, 'min_days': 8, 'multiplier': 1.5}}, help_text='Multiplicador de XP baseado na sequência de dias de registro de refeições completo')),
                ('months_to_end_season', models.IntegerField(default=2, help_text='Número de meses para finalizar a temporada, para concesão de bônus para usuários abaixo no ranking')),
                ('season_bonus_percentage', models.FloatField(default=50.0, help_text='Porcentagem de bônus de XP concedida aos usuários abaixo no ranking próximo do final da temporada')),
                ('percentage_from_first_position', models.FloatField(default=60.0, help_text='Porcentagem de pontos do primeiro colocado que deverão receber boônus de XP no final da temporada')),
            ],
            options={
                'verbose_name': 'Gamification Setting',
                'verbose_name_plural': 'Gamification Settings',
            },
        ),
    ]
