# Generated by Django 5.2.3 on 2025-10-18 19:17

import gamification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamificationsettings',
            name='multiplier_meal_streak',
            field=models.JSONField(default=gamification.models.default_multiplier_meal_streak, help_text='Multiplicador de XP baseado na sequência de dias de registro de refeições completo'),
        ),
        migrations.AlterField(
            model_name='gamificationsettings',
            name='multiplier_workout_streak',
            field=models.JSONField(default=gamification.models.default_multiplier_workout_streak, help_text='Multiplicador de XP baseado na sequência de dias de atividade'),
        ),
    ]
