# Generated by Django 5.2.3 on 2025-10-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_alter_gamificationsettings_multiplier_meal_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamificationsettings',
            name='singleton_id',
            field=models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
        ),
    ]
