# Generated by Django 5.2.3 on 2025-10-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_gamificationsettings_singleton_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome', max_length=100)),
                ('start_date', models.DateField(help_text='Data de início da temporada')),
                ('end_date', models.DateField(help_text='Data de término da temporada')),
                ('description', models.TextField(blank=True, help_text='Descrição da temporada')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
            },
        ),
    ]
