# Generated by Django 5.2.3 on 2025-10-20 12:59

import gamification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamificationsettings',
            name='multiplier_workout_streak',
            field=models.JSONField(default=gamification.models.default_multiplier_workout_streak, help_text='Multiplicador de XP baseado na sequência de treinos'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('start_date', 'end_date')},
        ),
    ]
