# Generated by Django 5.2.3 on 2025-10-20 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('gamification', '0005_alter_gamificationsettings_multiplier_workout_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='seasons', to='clients.client', verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='season',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição da temporada', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateField(help_text='Data de término da temporada', verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(help_text='Nome', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(help_text='Data de início da temporada', verbose_name='Data de Início'),
        ),
    ]
