# Generated by Django 5.2.3 on 2025-10-22 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('gamification', '0006_season_client_alter_season_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('client', 'start_date', 'end_date')},
        ),
    ]
