# Generated by Django 5.2.3 on 2025-10-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_alter_season_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamificationsettings',
            name='percentage_from_first_position',
            field=models.FloatField(default=60.0, help_text='Porcentagem de pontos do primeiro colocado que deverão receber bônus de XP no final da temporada'),
        ),
    ]
