# Generated by Django 5.2.3 on 2026-01-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0008_alter_gamificationsettings_percentage_from_first_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamificationsettings',
            name='max_workout_xp',
            field=models.IntegerField(default=4, help_text='XP máximo concedido por treino e por dia'),
        ),
        migrations.AlterField(
            model_name='gamificationsettings',
            name='workout_xp',
            field=models.IntegerField(default=2, help_text='XP concedido por completar exatos minutos de treino'),
        ),
    ]
