# Generated by Django 5.2.3 on 2026-03-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0009_gamificationsettings_max_workout_xp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamificationsettings',
            name='months_to_end_season',
        ),
        migrations.AddField(
            model_name='gamificationsettings',
            name='days_to_end_month',
            field=models.IntegerField(default=2, help_text='Número de dias para finalizar o mês, para concesão de bônus para usuários abaixo no ranking'),
        ),
    ]
