# Generated by Django 5.2.3 on 2026-03-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0010_remove_gamificationsettings_months_to_end_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamificationsettings',
            name='days_to_end_month',
            field=models.IntegerField(default=10, help_text='Número de dias para finalizar o mês, para concesão de bônus para usuários abaixo no ranking'),
        ),
    ]
