# Generated by Django 5.2.3 on 2026-03-21 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gamification', '0011_alter_gamificationsettings_days_to_end_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamificationBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Pontuacao de bonus aplicada ao objeto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_bonuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gamification Bonus',
                'verbose_name_plural': 'Gamification Bonuses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='gamificatio_user_id_3ed35b_idx'), models.Index(fields=['content_type', 'object_id'], name='gamificatio_content_4ac801_idx')],
            },
        ),
        migrations.CreateModel(
            name='GamificationPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Pontuacao de penalidade aplicada ao objeto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_penalties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gamification Penalty',
                'verbose_name_plural': 'Gamification Penalties',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='gamificatio_user_id_7d6286_idx'), models.Index(fields=['content_type', 'object_id'], name='gamificatio_content_d9355d_idx')],
            },
        ),
    ]
