# Generated by Django 5.2.3 on 2026-03-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0012_gamificationbonus_gamificationpenalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamificationbonus',
            name='reason',
            field=models.CharField(blank=True, help_text='Motivo do bônus', max_length=255, null=True, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='gamificationpenalty',
            name='reason',
            field=models.CharField(blank=True, help_text='Motivo da penalização', max_length=255, null=True, verbose_name='Motivo'),
        ),
    ]
