# Generated by Django 5.2.3 on 2026-03-21 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gamification', '0013_gamificationbonus_reason_gamificationpenalty_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gamificationbonus',
            name='gamificatio_user_id_3ed35b_idx',
        ),
        migrations.RemoveIndex(
            model_name='gamificationpenalty',
            name='gamificatio_user_id_7d6286_idx',
        ),
        migrations.RenameField(
            model_name='gamificationbonus',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='gamificationpenalty',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddIndex(
            model_name='gamificationbonus',
            index=models.Index(fields=['-created_at'], name='gamificatio_created_419c42_idx'),
        ),
        migrations.AddIndex(
            model_name='gamificationpenalty',
            index=models.Index(fields=['-created_at'], name='gamificatio_created_04e028_idx'),
        ),
    ]
