# Generated by Django 5.2.3 on 2025-07-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_groupmembers_group_alter_groupmembers_member_and_more'),
        ('profiles', '0002_alter_profile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, to='groups.group'),
        ),
    ]
