# Generated by Django 5.2.3 on 2025-08-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='streak_days',
        ),
    ]
