# Generated by Django 5.2.3 on 2025-10-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
