# Generated by Django 5.2.3 on 2025-10-24 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_client_code'),
        ('profiles', '0008_alter_profile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='clients.client'),
            preserve_default=False,
        ),
    ]
