# Generated by Django 5.2.3 on 2025-10-24 23:41

import django.db.models.deletion
from django.db import migrations, models, connection


def create_client(apps, schema_editor):
    Client = apps.get_model('clients', 'Client')
    User = apps.get_model('auth', 'User')

    # Obtém um usuário existente ou cria um mínimo sem forçar o id
    user, _ = User.objects.get_or_create(
        username='initial_admin',
        defaults={'email': 'admin@example.com'}
    )

    # Cria o client (ajuste campos conforme seu modelo)
    client = Client.objects.create(
        name='Test Client',
        cnpj='12.345.678/0002-90',
        owners=user,
        contact_email='contato@cliente.test',
        phone='(11)99999-9999',
        address='Rua Exemplo, 123, Bairro, Cidade - SP',
    )

    # Anexa o usuário como owner de forma segura (suporta M2M ou FK)
    owners_attr = getattr(client, 'owners', None)
    if owners_attr is not None:
        if hasattr(owners_attr, 'add'):
            owners_attr.add(user)
        else:
            setattr(client, 'owners', user)
            client.save()

    # Garante que a sequência do PostgreSQL está correta para evitar duplicatas
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT setval(pg_get_serial_sequence('auth_user','id'), GREATEST((SELECT MAX(id) FROM auth_user), 1))"
        )


class Migration(migrations.Migration):
    dependencies = [
        ('clients', '0004_client_client_code'),
        ('profiles', '0008_alter_profile_score'),
    ]

    operations = [
        migrations.RunPython(create_client),
        migrations.AddField(
            model_name='profile',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='employees',
                                    to='clients.client'),
            preserve_default=False,
        ),
    ]
