# Generated by Django 5.2.3 on 2025-11-18 04:29

import django.db.models.deletion
import social_feed.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition', '0002_alter_meal_user'),
        ('status', '0005_alter_status_app_name'),
        ('workouts', '0012_alter_workoutcheckin_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('workout', 'Workout'), ('meal', 'Meal'), ('social', 'Social')], max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('global', 'Global'), ('group', 'Group'), ('private', 'Private')], default='global', max_length=20)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('allow_comments', models.BooleanField(default=True)),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='nutrition.meal')),
                ('status', models.ForeignKey(default=social_feed.models.get_post_published_status_id, limit_choices_to={'app_name': 'POST', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('workout_checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='workouts.workoutcheckin')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(default=social_feed.models.get_comment_published_status_id, limit_choices_to={'app_name': 'COMMENT', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social_feed.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social_feed.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comentário')], max_length=10)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Conteúdo Inapropriado'), ('harassment', 'Assédio'), ('fake', 'Informação Falsa'), ('other', 'Outro')], max_length=20)),
                ('other_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('reviewed', 'Sob revisão'), ('resolved', 'Resolvido'), ('dismissed', 'Descartado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='social_feed.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='social_feed.post')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social_feed.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['comment', 'user'], name='social_feed_comment_f85499_idx'), models.Index(fields=['user', 'created_at'], name='social_feed_user_id_3fbdf4_idx')],
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', '-created_at'], name='social_feed_user_id_16b1a4_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['visibility', '-created_at'], name='social_feed_visibil_9d5d86_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['content_type', '-created_at'], name='social_feed_content_6be1fe_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='social_feed_post_id_588ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='social_feed_user_id_e43d18_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['post', 'user'], name='social_feed_post_id_08b4f6_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['user', 'created_at'], name='social_feed_user_id_739144_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('post', 'user')},
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='social_feed_status_c16612_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['post', '-created_at'], name='social_feed_post_id_664b71_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_by', '-created_at'], name='social_feed_reporte_a38e21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('post', 'reported_by')},
        ),
    ]
