# Generated by Django 5.2.3 on 2025-11-19 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content_text',
        ),
        migrations.AddField(
            model_name='post',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='post_media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg, jpeg, png, mp4, mov'])]),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('workout', 'Workout'), ('meal', 'Meal'), ('social', 'Social'), ('achievement', 'Achievement')], max_length=20),
        ),
    ]
