# Generated by Django 5.2.3 on 2025-11-19 20:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_feed', '0002_rename_content_post_content_text_post_content_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_file',
        ),
        migrations.CreateModel(
            name='ContentFilePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='post_media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4', 'mov'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_files', to='social_feed.post')),
            ],
            options={
                'indexes': [models.Index(fields=['post', 'uploaded_at'], name='social_feed_post_id_9a9229_idx')],
            },
        ),
    ]
