# Generated by Django 5.2.3 on 2025-11-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_feed', '0003_remove_post_content_file_contentfilepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
