# Generated by Django 5.2.3 on 2025-12-08 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_alter_meal_validation_status'),
        ('social_feed', '0004_comment_likes_count'),
        ('workouts', '0013_alter_workoutcheckin_validation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='nutrition.meal'),
        ),
        migrations.AlterField(
            model_name='post',
            name='workout_checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='workouts.workoutcheckin'),
        ),
    ]
